### ISSUE TITLE
Provide an afterRender callback

### ISSUE THREAD

**Issue by darrenbelding** [meanbee/magento2-infinitescroll#5]
Currently there is no way of knowing when knockout has updated it's observableArrays and finished inserting nodes. Having something similar to afterRender so that themes can hook into would be useful. e.g. image lazy loader

**Comment by fritzmg** [comment]
I like the concept of your extension and I'd love to continue using it - however I am also currently in need of such a callback, since my product list contains elements that require JavaScript initialization for example.

Are you still planning on maintaining and extending this extension? Otherwise I'd fork and try to extend it myself (and provide Pull Requests). However, I am not sure how to integrate the callback, since I don't quite understand how the Magento_UI component works in combination with Knockout.js

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
